// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcmwpbgdehtuqxcjqmxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjbXdwYmdkZWh0dXF4Y2pxbXhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MjI0NzgsImV4cCI6MjA3MDA5ODQ3OH0.QSemqy75-ecUs11I3S647MAxa1Egjkx8UEmR6IuzaXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});